services:
  istl:
    image: istl_fedora:latest
    hostname: istl
    container_name: istl
    restart: always
    expose:
      - 22
    ports:
      - 2222:22
    volumes:
      - type: bind
        source: ./mounts/trainee_home
        target: /home/trainee
      - type: bind
        source: ./mounts/usr_local_bin
        target: /usr/local/bin
      - type: bind
        source: ./mounts/mnt_host
        target: /mnt/host
  istl_flask:
    image: istl_flask:latest
    hostname: istl_flask
    container_name: istl_flask
    expose:
      - 5000
    ports:
      - 8000:5000
    restart: always
    volumes:
      - type: bind
        source: ./mounts/flask
        target: /flask
  istl_server:
    image: istl_fedora:latest
    hostname: rmtlnx1000
    container_name: istl_server
    restart: always
    expose:
      - 22
    ports:
      - 2223:22
      
  wetty:
    image: wetty
    hostname: wetty
    container_name: wetty
    restart: always
    expose:
      - 3000
      - 22
    ports:
      - 3000:3000
      - 2224:22    
