#!/bin/bash

FILMS="alien django_unchained inglourious_basterds jackie_brown once_upon_a_time_in_hollywood reservoir_dogs the_hateful_seven the_thing kill_bill_1 kill_bill_2 pulp_fiction"
RESULT=""

for FILM in $FILMS; do
	if [ -e "/home/trainee/chapter_1/tarantino/${FILM}" ] && [ ! -e "/home/trainee/chapter_1/Files/${FILM}" ]
	then
		RESULT="correct"
  	else
    	RESULT="incorrect"
		break
	fi
done

echo $RESULT
