#!/bin/bash

file1="/home/trainee/chapter_5/warty-release-install-powerpc.jigdo"
file2="/usr/local/bin/files/warty-release-install-powerpc.jigdo"

if cmp -s "$file1" "$file2"; then
    echo "correct"
else
    echo "incorrect"
fi
